# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo '$(Build.BinariesDirectory)'
    echo '$(Build.ArtifactStagingDirectory)'
    echo '$(Build.BuildId)'
  displayName: 'Run a multi-line script'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    workingDirectory: 'Thor'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'Sif'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'Sif'
    customCommand: 'run build-minor'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

