# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo '$(Build.BuildId)'
  displayName: 'Run a multi-line script'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration Release'
    workingDirectory: 'Thor'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'Sif'

- task: FileTransform@1
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/Sif/'
    fileType: 'json'
    targetFiles: 'auth_config'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'Sif'
    customCommand: 'run build-minor'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'Thor/bin/Release/netcoreapp3.1'
    artifact: 'Thor'
    publishLocation: 'pipeline'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'Sif/dist'
    artifact: 'Sif'
    publishLocation: 'pipeline'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'Database'
    artifact: 'Database'
    publishLocation: 'pipeline'

