version: "3.7"
services:
  mariadb:
    image: mariadb:latest
    volumes: 
      - database:/var/lib/docker/volumes/database/_data
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
    networks: 
      backend:
        ipv4_address: 172.40.0.6

  thor:
    build: 
     context: .
     dockerfile: ./Thor/Dockerfile
    volumes:
      - uploads:/app/uploads
    networks: 
      frontend:
        ipv4_address: 172.30.0.6
      backend:
        ipv4_address: 172.40.0.4
  
  sif:
    build:
      context: ./Sif
      dockerfile: Dockerfile
    environment: 
      BACKEND: http://172.30.0.6
    #volumes:
    #  - ./certbot/www:/var/www/certbot/:ro
    #  - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports: 
      - "80:80"
      - "443:443"
    networks: 
      - frontend

  #certbot:
  #  image: certbot/certbot:latest
  #  volumes:
  #    - ./certbot/www/:/var/www/certbot/:rw
  #    - ./certbot/conf/:/etc/letsencrypt/:rw'

volumes:
    database:
    uploads:

networks: 
  frontend:
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: 172.30.0.0/29
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.40.0.0/29